
# 使用官方的 Nginx 镜像
FROM nginx:latest

# 删除默认的 Nginx 配置文件
RUN rm /etc/nginx/conf.d/default.conf

# 复制自定义的 Nginx 配置文件到容器中
COPY nginx.local.conf /etc/nginx/conf.d/nginx.conf

COPY local-ssl/mylocal.crt /etc/ssl/certs
COPY local-ssl/mylocal.key /etc/ssl/certs
COPY local-ssl/mylocal.csr /etc/ssl/certs
COPY local-ssl/dhparam.pem /etc/ssl/ssl-dhparams.pem
COPY local-ssl/options-ssl-nginx.conf /etc/ssl


# 复制网站文件到容器中
COPY site-content/ /usr/share/nginx/html
